//
// Generated by Bluespec Compiler, version 2025.01.1-9-g76db531e (build 76db531e)
//
// On Mon Jul 28 19:05:14 PDT 2025
//
//
// Ports:
// Name                         I/O  size props
// RDY_enq                        O     1 const
// RDY_deq                        O     1 const
// first                          O    32
// RDY_first                      O     1 const
// notFull                        O     1
// RDY_notFull                    O     1 const
// notEmpty                       O     1
// RDY_notEmpty                   O     1 const
// count                          O     3 reg
// RDY_count                      O     1 const
// RDY_clear                      O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// enq_sendData                   I    32 reg
// EN_enq                         I     1
// EN_deq                         I     1
// EN_clear                       I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRegFIFOSynth(CLK,
		      RST_N,

		      enq_sendData,
		      EN_enq,
		      RDY_enq,

		      EN_deq,
		      RDY_deq,

		      first,
		      RDY_first,

		      notFull,
		      RDY_notFull,

		      notEmpty,
		      RDY_notEmpty,

		      count,
		      RDY_count,

		      EN_clear,
		      RDY_clear);
  input  CLK;
  input  RST_N;

  // action method enq
  input  [31 : 0] enq_sendData;
  input  EN_enq;
  output RDY_enq;

  // action method deq
  input  EN_deq;
  output RDY_deq;

  // value method first
  output [31 : 0] first;
  output RDY_first;

  // value method notFull
  output notFull;
  output RDY_notFull;

  // value method notEmpty
  output notEmpty;
  output RDY_notEmpty;

  // value method count
  output [2 : 0] count;
  output RDY_count;

  // action method clear
  input  EN_clear;
  output RDY_clear;

  // signals for module outputs
  reg [31 : 0] first;
  wire [2 : 0] count;
  wire RDY_clear,
       RDY_count,
       RDY_deq,
       RDY_enq,
       RDY_first,
       RDY_notEmpty,
       RDY_notFull,
       notEmpty,
       notFull;

  // register f_fifo_almost_full
  reg f_fifo_almost_full;
  wire f_fifo_almost_full$D_IN, f_fifo_almost_full$EN;

  // register f_fifo_deq_cnt
  reg [63 : 0] f_fifo_deq_cnt;
  wire [63 : 0] f_fifo_deq_cnt$D_IN;
  wire f_fifo_deq_cnt$EN;

  // register f_fifo_empty
  reg f_fifo_empty;
  wire f_fifo_empty$D_IN, f_fifo_empty$EN;

  // register f_fifo_enq_cnt
  reg [63 : 0] f_fifo_enq_cnt;
  wire [63 : 0] f_fifo_enq_cnt$D_IN;
  wire f_fifo_enq_cnt$EN;

  // register f_fifo_full
  reg f_fifo_full;
  wire f_fifo_full$D_IN, f_fifo_full$EN;

  // register f_fifo_head
  reg [1 : 0] f_fifo_head;
  wire [1 : 0] f_fifo_head$D_IN;
  wire f_fifo_head$EN;

  // register f_fifo_mem_0
  reg [31 : 0] f_fifo_mem_0;
  wire [31 : 0] f_fifo_mem_0$D_IN;
  wire f_fifo_mem_0$EN;

  // register f_fifo_mem_1
  reg [31 : 0] f_fifo_mem_1;
  wire [31 : 0] f_fifo_mem_1$D_IN;
  wire f_fifo_mem_1$EN;

  // register f_fifo_mem_2
  reg [31 : 0] f_fifo_mem_2;
  wire [31 : 0] f_fifo_mem_2$D_IN;
  wire f_fifo_mem_2$EN;

  // register f_fifo_mem_3
  reg [31 : 0] f_fifo_mem_3;
  wire [31 : 0] f_fifo_mem_3$D_IN;
  wire f_fifo_mem_3$EN;

  // register f_fifo_size_cnt
  reg [2 : 0] f_fifo_size_cnt;
  wire [2 : 0] f_fifo_size_cnt$D_IN;
  wire f_fifo_size_cnt$EN;

  // register f_fifo_tail
  reg [1 : 0] f_fifo_tail;
  wire [1 : 0] f_fifo_tail$D_IN;
  wire f_fifo_tail$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_f_fifo_continuousAssert;

  // remaining internal signals
  wire [63 : 0] x__h1535, x__h948;
  wire [2 : 0] IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d48,
	       IF_f_fifo_w_deq_whas_THEN_f_fifo_size_cnt_3_MI_ETC___d47;
  wire [1 : 0] x__h1700, x__h1776, x__h1833;
  wire IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d25,
       IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d33,
       IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d41,
       IF_f_fifo_w_deq_whas_THEN_f_fifo_head_PLUS_1_E_ETC___d40,
       IF_f_fifo_w_deq_whas_THEN_f_fifo_tail_EQ_f_fif_ETC___d32,
       IF_f_fifo_w_enq_whas_THEN_f_fifo_tail_PLUS_1_0_ETC___d23,
       IF_f_fifo_w_enq_whas_THEN_f_fifo_tail_PLUS_2_9_ETC___d31,
       f_fifo_empty_6_EQ_f_fifo_head_EQ_f_fifo_tail_4_ETC___d67;

  // action method enq
  assign RDY_enq = 1'd1 ;

  // action method deq
  assign RDY_deq = 1'd1 ;

  // value method first
  always@(f_fifo_head or
	  f_fifo_mem_0 or f_fifo_mem_1 or f_fifo_mem_2 or f_fifo_mem_3)
  begin
    case (f_fifo_head)
      2'd0: first = f_fifo_mem_0;
      2'd1: first = f_fifo_mem_1;
      2'd2: first = f_fifo_mem_2;
      2'd3: first = f_fifo_mem_3;
    endcase
  end
  assign RDY_first = 1'd1 ;

  // value method notFull
  assign notFull = !f_fifo_full ;
  assign RDY_notFull = 1'd1 ;

  // value method notEmpty
  assign notEmpty = !f_fifo_empty ;
  assign RDY_notEmpty = 1'd1 ;

  // value method count
  assign count = f_fifo_size_cnt ;
  assign RDY_count = 1'd1 ;

  // action method clear
  assign RDY_clear = 1'd1 ;

  // rule RL_f_fifo_continuousAssert
  assign WILL_FIRE_RL_f_fifo_continuousAssert =
	     f_fifo_empty && f_fifo_enq_cnt != f_fifo_deq_cnt ;

  // register f_fifo_almost_full
  assign f_fifo_almost_full$D_IN =
	     !EN_clear &&
	     (IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d33 ||
	      IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d25) ;
  assign f_fifo_almost_full$EN = 1'd1 ;

  // register f_fifo_deq_cnt
  assign f_fifo_deq_cnt$D_IN = EN_clear ? 64'd0 : x__h948 ;
  assign f_fifo_deq_cnt$EN = EN_clear || EN_deq ;

  // register f_fifo_empty
  assign f_fifo_empty$D_IN =
	     EN_clear ||
	     IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d41 ;
  assign f_fifo_empty$EN = 1'd1 ;

  // register f_fifo_enq_cnt
  assign f_fifo_enq_cnt$D_IN = EN_clear ? 64'd0 : x__h1535 ;
  assign f_fifo_enq_cnt$EN = EN_clear || EN_enq ;

  // register f_fifo_full
  assign f_fifo_full$D_IN =
	     !EN_clear &&
	     IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d25 ;
  assign f_fifo_full$EN = 1'd1 ;

  // register f_fifo_head
  assign f_fifo_head$D_IN = EN_clear ? 2'd0 : x__h1700 ;
  assign f_fifo_head$EN = EN_clear || EN_deq ;

  // register f_fifo_mem_0
  assign f_fifo_mem_0$D_IN = enq_sendData ;
  assign f_fifo_mem_0$EN = f_fifo_tail == 2'd0 && !EN_clear && EN_enq ;

  // register f_fifo_mem_1
  assign f_fifo_mem_1$D_IN = enq_sendData ;
  assign f_fifo_mem_1$EN = f_fifo_tail == 2'd1 && !EN_clear && EN_enq ;

  // register f_fifo_mem_2
  assign f_fifo_mem_2$D_IN = enq_sendData ;
  assign f_fifo_mem_2$EN = f_fifo_tail == 2'd2 && !EN_clear && EN_enq ;

  // register f_fifo_mem_3
  assign f_fifo_mem_3$D_IN = enq_sendData ;
  assign f_fifo_mem_3$EN = f_fifo_tail == 2'd3 && !EN_clear && EN_enq ;

  // register f_fifo_size_cnt
  assign f_fifo_size_cnt$D_IN =
	     EN_clear ?
	       3'd0 :
	       IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d48 ;
  assign f_fifo_size_cnt$EN = 1'd1 ;

  // register f_fifo_tail
  assign f_fifo_tail$D_IN = EN_clear ? 2'd0 : x__h1776 ;
  assign f_fifo_tail$EN = EN_clear || EN_enq ;

  // remaining internal signals
  assign IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d25 =
	     (EN_deq && EN_enq) ?
	       f_fifo_full :
	       !EN_deq &&
	       IF_f_fifo_w_enq_whas_THEN_f_fifo_tail_PLUS_1_0_ETC___d23 ;
  assign IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d33 =
	     (EN_deq && EN_enq) ?
	       f_fifo_almost_full :
	       IF_f_fifo_w_deq_whas_THEN_f_fifo_tail_EQ_f_fif_ETC___d32 ;
  assign IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d41 =
	     (EN_deq && EN_enq) ?
	       f_fifo_empty :
	       IF_f_fifo_w_deq_whas_THEN_f_fifo_head_PLUS_1_E_ETC___d40 ;
  assign IF_f_fifo_w_deq_whas_AND_f_fifo_w_enq_whas_9_T_ETC___d48 =
	     (EN_deq && EN_enq) ?
	       f_fifo_size_cnt :
	       IF_f_fifo_w_deq_whas_THEN_f_fifo_size_cnt_3_MI_ETC___d47 ;
  assign IF_f_fifo_w_deq_whas_THEN_f_fifo_head_PLUS_1_E_ETC___d40 =
	     EN_deq ? x__h1700 == f_fifo_tail : !EN_enq && f_fifo_empty ;
  assign IF_f_fifo_w_deq_whas_THEN_f_fifo_size_cnt_3_MI_ETC___d47 =
	     EN_deq ?
	       f_fifo_size_cnt - 3'd1 :
	       (EN_enq ? f_fifo_size_cnt + 3'd1 : f_fifo_size_cnt) ;
  assign IF_f_fifo_w_deq_whas_THEN_f_fifo_tail_EQ_f_fif_ETC___d32 =
	     EN_deq ?
	       f_fifo_tail == f_fifo_head :
	       IF_f_fifo_w_enq_whas_THEN_f_fifo_tail_PLUS_2_9_ETC___d31 ;
  assign IF_f_fifo_w_enq_whas_THEN_f_fifo_tail_PLUS_1_0_ETC___d23 =
	     EN_enq ? x__h1776 == f_fifo_head : f_fifo_full ;
  assign IF_f_fifo_w_enq_whas_THEN_f_fifo_tail_PLUS_2_9_ETC___d31 =
	     EN_enq ? x__h1833 == f_fifo_head : f_fifo_almost_full ;
  assign f_fifo_empty_6_EQ_f_fifo_head_EQ_f_fifo_tail_4_ETC___d67 =
	     f_fifo_empty == (f_fifo_head == f_fifo_tail && !f_fifo_full) ;
  assign x__h1535 = f_fifo_enq_cnt + 64'd1 ;
  assign x__h1700 = f_fifo_head + 2'd1 ;
  assign x__h1776 = f_fifo_tail + 2'd1 ;
  assign x__h1833 = f_fifo_tail + 2'd2 ;
  assign x__h948 = f_fifo_deq_cnt + 64'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        f_fifo_almost_full <= `BSV_ASSIGNMENT_DELAY 1'd0;
	f_fifo_deq_cnt <= `BSV_ASSIGNMENT_DELAY 64'd0;
	f_fifo_empty <= `BSV_ASSIGNMENT_DELAY 1'd1;
	f_fifo_enq_cnt <= `BSV_ASSIGNMENT_DELAY 64'd0;
	f_fifo_full <= `BSV_ASSIGNMENT_DELAY 1'd0;
	f_fifo_head <= `BSV_ASSIGNMENT_DELAY 2'd0;
	f_fifo_mem_0 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	f_fifo_mem_1 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	f_fifo_mem_2 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	f_fifo_mem_3 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	f_fifo_size_cnt <= `BSV_ASSIGNMENT_DELAY 3'd0;
	f_fifo_tail <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (f_fifo_almost_full$EN)
	  f_fifo_almost_full <= `BSV_ASSIGNMENT_DELAY f_fifo_almost_full$D_IN;
	if (f_fifo_deq_cnt$EN)
	  f_fifo_deq_cnt <= `BSV_ASSIGNMENT_DELAY f_fifo_deq_cnt$D_IN;
	if (f_fifo_empty$EN)
	  f_fifo_empty <= `BSV_ASSIGNMENT_DELAY f_fifo_empty$D_IN;
	if (f_fifo_enq_cnt$EN)
	  f_fifo_enq_cnt <= `BSV_ASSIGNMENT_DELAY f_fifo_enq_cnt$D_IN;
	if (f_fifo_full$EN)
	  f_fifo_full <= `BSV_ASSIGNMENT_DELAY f_fifo_full$D_IN;
	if (f_fifo_head$EN)
	  f_fifo_head <= `BSV_ASSIGNMENT_DELAY f_fifo_head$D_IN;
	if (f_fifo_mem_0$EN)
	  f_fifo_mem_0 <= `BSV_ASSIGNMENT_DELAY f_fifo_mem_0$D_IN;
	if (f_fifo_mem_1$EN)
	  f_fifo_mem_1 <= `BSV_ASSIGNMENT_DELAY f_fifo_mem_1$D_IN;
	if (f_fifo_mem_2$EN)
	  f_fifo_mem_2 <= `BSV_ASSIGNMENT_DELAY f_fifo_mem_2$D_IN;
	if (f_fifo_mem_3$EN)
	  f_fifo_mem_3 <= `BSV_ASSIGNMENT_DELAY f_fifo_mem_3$D_IN;
	if (f_fifo_size_cnt$EN)
	  f_fifo_size_cnt <= `BSV_ASSIGNMENT_DELAY f_fifo_size_cnt$D_IN;
	if (f_fifo_tail$EN)
	  f_fifo_tail <= `BSV_ASSIGNMENT_DELAY f_fifo_tail$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    f_fifo_almost_full = 1'h0;
    f_fifo_deq_cnt = 64'hAAAAAAAAAAAAAAAA;
    f_fifo_empty = 1'h0;
    f_fifo_enq_cnt = 64'hAAAAAAAAAAAAAAAA;
    f_fifo_full = 1'h0;
    f_fifo_head = 2'h2;
    f_fifo_mem_0 = 32'hAAAAAAAA;
    f_fifo_mem_1 = 32'hAAAAAAAA;
    f_fifo_mem_2 = 32'hAAAAAAAA;
    f_fifo_mem_3 = 32'hAAAAAAAA;
    f_fifo_size_cnt = 3'h2;
    f_fifo_tail = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_enq && f_fifo_full)
	$display("location of dfifo: ",
		 "\"RegFIFO.bsv\", line 25, column 33\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_enq && f_fifo_full)
	$display("Dynamic assertion failed: \"RegFIFO.bsv\", line 191, column 27\nouch, enqueuing to full FIFO");
    if (RST_N != `BSV_RESET_VALUE) if (EN_enq && f_fifo_full) $finish(32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_deq && f_fifo_empty)
	$display("location of dfifo: ",
		 "\"RegFIFO.bsv\", line 25, column 33\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_deq && f_fifo_empty)
	$display("Dynamic assertion failed: \"RegFIFO.bsv\", line 198, column 28\nouch, dequeueing from empty FIFO");
    if (RST_N != `BSV_RESET_VALUE) if (EN_deq && f_fifo_empty) $finish(32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_f_fifo_continuousAssert)
	$display("Continuous assertion failed: \"RegFIFO.bsv\", line 167, column 59\nmismatched in enq/deq count");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_f_fifo_continuousAssert) $finish(32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (!f_fifo_empty_6_EQ_f_fifo_head_EQ_f_fifo_tail_4_ETC___d67)
	$display("Continuous assertion failed: \"RegFIFO.bsv\", line 170, column 45\nerror in empty signals");
    if (RST_N != `BSV_RESET_VALUE)
      if (!f_fifo_empty_6_EQ_f_fifo_head_EQ_f_fifo_tail_4_ETC___d67)
	$finish(32'd0);
  end
  // synopsys translate_on
endmodule  // mkRegFIFOSynth

