//
// Generated by Bluespec Compiler, version 2025.01.1-9-g76db531e (build 76db531e)
//
// On Thu Jul 31 18:29:07 PDT 2025
//
//
// Ports:
// Name                         I/O  size props
// output_arbs_0_select           O     5
// output_arbs_1_select           O     5
// output_arbs_2_select           O     5
// output_arbs_3_select           O     5
// output_arbs_4_select           O     5
// CLK                            I     1 clock
// RST_N                          I     1 reset
// output_arbs_0_select_requests  I     5
// output_arbs_1_select_requests  I     5
// output_arbs_2_select_requests  I     5
// output_arbs_3_select_requests  I     5
// output_arbs_4_select_requests  I     5
// EN_output_arbs_0_next          I     1
// EN_output_arbs_1_next          I     1
// EN_output_arbs_2_next          I     1
// EN_output_arbs_3_next          I     1
// EN_output_arbs_4_next          I     1
//
// Combinational paths from inputs to outputs:
//   output_arbs_0_select_requests -> output_arbs_0_select
//   output_arbs_1_select_requests -> output_arbs_1_select
//   output_arbs_2_select_requests -> output_arbs_2_select
//   output_arbs_3_select_requests -> output_arbs_3_select
//   output_arbs_4_select_requests -> output_arbs_4_select
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRouterOutputArbitersRoundRobin(CLK,
					RST_N,

					output_arbs_0_select_requests,
					output_arbs_0_select,

					EN_output_arbs_0_next,

					output_arbs_1_select_requests,
					output_arbs_1_select,

					EN_output_arbs_1_next,

					output_arbs_2_select_requests,
					output_arbs_2_select,

					EN_output_arbs_2_next,

					output_arbs_3_select_requests,
					output_arbs_3_select,

					EN_output_arbs_3_next,

					output_arbs_4_select_requests,
					output_arbs_4_select,

					EN_output_arbs_4_next);
  input  CLK;
  input  RST_N;

  // value method output_arbs_0_select
  input  [4 : 0] output_arbs_0_select_requests;
  output [4 : 0] output_arbs_0_select;

  // action method output_arbs_0_next
  input  EN_output_arbs_0_next;

  // value method output_arbs_1_select
  input  [4 : 0] output_arbs_1_select_requests;
  output [4 : 0] output_arbs_1_select;

  // action method output_arbs_1_next
  input  EN_output_arbs_1_next;

  // value method output_arbs_2_select
  input  [4 : 0] output_arbs_2_select_requests;
  output [4 : 0] output_arbs_2_select;

  // action method output_arbs_2_next
  input  EN_output_arbs_2_next;

  // value method output_arbs_3_select
  input  [4 : 0] output_arbs_3_select_requests;
  output [4 : 0] output_arbs_3_select;

  // action method output_arbs_3_next
  input  EN_output_arbs_3_next;

  // value method output_arbs_4_select
  input  [4 : 0] output_arbs_4_select_requests;
  output [4 : 0] output_arbs_4_select;

  // action method output_arbs_4_next
  input  EN_output_arbs_4_next;

  // signals for module outputs
  wire [4 : 0] output_arbs_0_select,
	       output_arbs_1_select,
	       output_arbs_2_select,
	       output_arbs_3_select,
	       output_arbs_4_select;

  // register oas_0_token
  reg [4 : 0] oas_0_token;
  wire [4 : 0] oas_0_token$D_IN;
  wire oas_0_token$EN;

  // register oas_1_token
  reg [4 : 0] oas_1_token;
  wire [4 : 0] oas_1_token$D_IN;
  wire oas_1_token$EN;

  // register oas_2_token
  reg [4 : 0] oas_2_token;
  wire [4 : 0] oas_2_token$D_IN;
  wire oas_2_token$EN;

  // register oas_3_token
  reg [4 : 0] oas_3_token;
  wire [4 : 0] oas_3_token$D_IN;
  wire oas_3_token$EN;

  // register oas_4_token
  reg [4 : 0] oas_4_token;
  wire [4 : 0] oas_4_token$D_IN;
  wire oas_4_token$EN;

  // remaining internal signals
  wire [1 : 0] gen_grant_carry___d101,
	       gen_grant_carry___d12,
	       gen_grant_carry___d144,
	       gen_grant_carry___d148,
	       gen_grant_carry___d152,
	       gen_grant_carry___d156,
	       gen_grant_carry___d16,
	       gen_grant_carry___d160,
	       gen_grant_carry___d163,
	       gen_grant_carry___d165,
	       gen_grant_carry___d167,
	       gen_grant_carry___d169,
	       gen_grant_carry___d171,
	       gen_grant_carry___d20,
	       gen_grant_carry___d214,
	       gen_grant_carry___d218,
	       gen_grant_carry___d222,
	       gen_grant_carry___d226,
	       gen_grant_carry___d23,
	       gen_grant_carry___d230,
	       gen_grant_carry___d233,
	       gen_grant_carry___d235,
	       gen_grant_carry___d237,
	       gen_grant_carry___d239,
	       gen_grant_carry___d241,
	       gen_grant_carry___d25,
	       gen_grant_carry___d27,
	       gen_grant_carry___d284,
	       gen_grant_carry___d288,
	       gen_grant_carry___d29,
	       gen_grant_carry___d292,
	       gen_grant_carry___d296,
	       gen_grant_carry___d300,
	       gen_grant_carry___d303,
	       gen_grant_carry___d305,
	       gen_grant_carry___d307,
	       gen_grant_carry___d309,
	       gen_grant_carry___d31,
	       gen_grant_carry___d311,
	       gen_grant_carry___d4,
	       gen_grant_carry___d74,
	       gen_grant_carry___d78,
	       gen_grant_carry___d8,
	       gen_grant_carry___d82,
	       gen_grant_carry___d86,
	       gen_grant_carry___d90,
	       gen_grant_carry___d93,
	       gen_grant_carry___d95,
	       gen_grant_carry___d97,
	       gen_grant_carry___d99;
  wire NOT_gen_grant_carry_00_BIT_1_01_14_AND_NOT_gen_ETC___d328,
       NOT_gen_grant_carry_00_BIT_1_01_14_AND_NOT_gen_ETC___d348,
       NOT_gen_grant_carry_0_BIT_1_1_04_AND_NOT_gen_g_ETC___d118,
       NOT_gen_grant_carry_0_BIT_1_1_04_AND_NOT_gen_g_ETC___d138,
       NOT_gen_grant_carry_0_BIT_1_1_4_AND_NOT_gen_gr_ETC___d48,
       NOT_gen_grant_carry_0_BIT_1_1_4_AND_NOT_gen_gr_ETC___d68,
       NOT_gen_grant_carry_22_BIT_1_54_60_AND_NOT_gen_ETC___d276,
       NOT_gen_grant_carry_26_BIT_1_47_51_AND_NOT_gen_ETC___d267,
       NOT_gen_grant_carry_2_BIT_1_14_20_AND_NOT_gen__ETC___d136,
       NOT_gen_grant_carry_2_BIT_1_4_0_AND_NOT_gen_gr_ETC___d66,
       NOT_gen_grant_carry_30_BIT_1_31_44_AND_NOT_gen_ETC___d258,
       NOT_gen_grant_carry_30_BIT_1_31_44_AND_NOT_gen_ETC___d278,
       NOT_gen_grant_carry_52_BIT_1_84_90_AND_NOT_gen_ETC___d206,
       NOT_gen_grant_carry_56_BIT_1_77_81_AND_NOT_gen_ETC___d197,
       NOT_gen_grant_carry_60_BIT_1_61_74_AND_NOT_gen_ETC___d188,
       NOT_gen_grant_carry_60_BIT_1_61_74_AND_NOT_gen_ETC___d208,
       NOT_gen_grant_carry_6_BIT_1_07_11_AND_NOT_gen__ETC___d127,
       NOT_gen_grant_carry_6_BIT_1_7_1_AND_NOT_gen_gr_ETC___d57,
       NOT_gen_grant_carry_92_BIT_1_24_30_AND_NOT_gen_ETC___d346,
       NOT_gen_grant_carry_96_BIT_1_17_21_AND_NOT_gen_ETC___d337,
       oas_0_token_BIT_0___h4581,
       oas_0_token_BIT_1___h4647,
       oas_0_token_BIT_2___h4713,
       oas_0_token_BIT_3___h4779,
       oas_0_token_BIT_4___h4845,
       oas_1_token_BIT_0___h9561,
       oas_1_token_BIT_1___h9627,
       oas_1_token_BIT_2___h9693,
       oas_1_token_BIT_3___h9759,
       oas_1_token_BIT_4___h9825,
       oas_2_token_BIT_0___h14538,
       oas_2_token_BIT_1___h14604,
       oas_2_token_BIT_2___h14670,
       oas_2_token_BIT_3___h14736,
       oas_2_token_BIT_4___h14802,
       oas_3_token_BIT_0___h19515,
       oas_3_token_BIT_1___h19581,
       oas_3_token_BIT_2___h19647,
       oas_3_token_BIT_3___h19713,
       oas_3_token_BIT_4___h19779,
       oas_4_token_BIT_0___h24492,
       oas_4_token_BIT_1___h24558,
       oas_4_token_BIT_2___h24624,
       oas_4_token_BIT_3___h24690,
       oas_4_token_BIT_4___h24756;

  // value method output_arbs_0_select
  assign output_arbs_0_select =
	     { gen_grant_carry___d20[1] || gen_grant_carry___d31[1],
	       !gen_grant_carry___d20[1] && !gen_grant_carry___d31[1] &&
	       (gen_grant_carry___d16[1] || gen_grant_carry___d29[1]),
	       NOT_gen_grant_carry_0_BIT_1_1_4_AND_NOT_gen_gr_ETC___d48,
	       !gen_grant_carry___d20[1] && !gen_grant_carry___d31[1] &&
	       NOT_gen_grant_carry_6_BIT_1_7_1_AND_NOT_gen_gr_ETC___d57,
	       NOT_gen_grant_carry_0_BIT_1_1_4_AND_NOT_gen_gr_ETC___d68 } ;

  // value method output_arbs_1_select
  assign output_arbs_1_select =
	     { gen_grant_carry___d90[1] || gen_grant_carry___d101[1],
	       !gen_grant_carry___d90[1] && !gen_grant_carry___d101[1] &&
	       (gen_grant_carry___d86[1] || gen_grant_carry___d99[1]),
	       NOT_gen_grant_carry_0_BIT_1_1_04_AND_NOT_gen_g_ETC___d118,
	       !gen_grant_carry___d90[1] && !gen_grant_carry___d101[1] &&
	       NOT_gen_grant_carry_6_BIT_1_07_11_AND_NOT_gen__ETC___d127,
	       NOT_gen_grant_carry_0_BIT_1_1_04_AND_NOT_gen_g_ETC___d138 } ;

  // value method output_arbs_2_select
  assign output_arbs_2_select =
	     { gen_grant_carry___d160[1] || gen_grant_carry___d171[1],
	       !gen_grant_carry___d160[1] && !gen_grant_carry___d171[1] &&
	       (gen_grant_carry___d156[1] || gen_grant_carry___d169[1]),
	       NOT_gen_grant_carry_60_BIT_1_61_74_AND_NOT_gen_ETC___d188,
	       !gen_grant_carry___d160[1] && !gen_grant_carry___d171[1] &&
	       NOT_gen_grant_carry_56_BIT_1_77_81_AND_NOT_gen_ETC___d197,
	       NOT_gen_grant_carry_60_BIT_1_61_74_AND_NOT_gen_ETC___d208 } ;

  // value method output_arbs_3_select
  assign output_arbs_3_select =
	     { gen_grant_carry___d230[1] || gen_grant_carry___d241[1],
	       !gen_grant_carry___d230[1] && !gen_grant_carry___d241[1] &&
	       (gen_grant_carry___d226[1] || gen_grant_carry___d239[1]),
	       NOT_gen_grant_carry_30_BIT_1_31_44_AND_NOT_gen_ETC___d258,
	       !gen_grant_carry___d230[1] && !gen_grant_carry___d241[1] &&
	       NOT_gen_grant_carry_26_BIT_1_47_51_AND_NOT_gen_ETC___d267,
	       NOT_gen_grant_carry_30_BIT_1_31_44_AND_NOT_gen_ETC___d278 } ;

  // value method output_arbs_4_select
  assign output_arbs_4_select =
	     { gen_grant_carry___d300[1] || gen_grant_carry___d311[1],
	       !gen_grant_carry___d300[1] && !gen_grant_carry___d311[1] &&
	       (gen_grant_carry___d296[1] || gen_grant_carry___d309[1]),
	       NOT_gen_grant_carry_00_BIT_1_01_14_AND_NOT_gen_ETC___d328,
	       !gen_grant_carry___d300[1] && !gen_grant_carry___d311[1] &&
	       NOT_gen_grant_carry_96_BIT_1_17_21_AND_NOT_gen_ETC___d337,
	       NOT_gen_grant_carry_00_BIT_1_01_14_AND_NOT_gen_ETC___d348 } ;

  // register oas_0_token
  assign oas_0_token$D_IN = { oas_0_token[0], oas_0_token[4:1] } ;
  assign oas_0_token$EN = EN_output_arbs_0_next ;

  // register oas_1_token
  assign oas_1_token$D_IN = { oas_1_token[0], oas_1_token[4:1] } ;
  assign oas_1_token$EN = EN_output_arbs_1_next ;

  // register oas_2_token
  assign oas_2_token$D_IN = { oas_2_token[0], oas_2_token[4:1] } ;
  assign oas_2_token$EN = EN_output_arbs_2_next ;

  // register oas_3_token
  assign oas_3_token$D_IN = { oas_3_token[0], oas_3_token[4:1] } ;
  assign oas_3_token$EN = EN_output_arbs_3_next ;

  // register oas_4_token
  assign oas_4_token$D_IN = { oas_4_token[0], oas_4_token[4:1] } ;
  assign oas_4_token$EN = EN_output_arbs_4_next ;

  // remaining internal signals
  module_gen_grant_carry instance_gen_grant_carry_45(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(output_arbs_0_select_requests[0]),
						     .gen_grant_carry_p(oas_0_token_BIT_0___h4581),
						     .gen_grant_carry(gen_grant_carry___d4));
  module_gen_grant_carry instance_gen_grant_carry_46(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(output_arbs_1_select_requests[0]),
						     .gen_grant_carry_p(oas_1_token_BIT_0___h9561),
						     .gen_grant_carry(gen_grant_carry___d74));
  module_gen_grant_carry instance_gen_grant_carry_47(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(output_arbs_2_select_requests[0]),
						     .gen_grant_carry_p(oas_2_token_BIT_0___h14538),
						     .gen_grant_carry(gen_grant_carry___d144));
  module_gen_grant_carry instance_gen_grant_carry_48(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(output_arbs_3_select_requests[0]),
						     .gen_grant_carry_p(oas_3_token_BIT_0___h19515),
						     .gen_grant_carry(gen_grant_carry___d214));
  module_gen_grant_carry instance_gen_grant_carry_49(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(output_arbs_4_select_requests[0]),
						     .gen_grant_carry_p(oas_4_token_BIT_0___h24492),
						     .gen_grant_carry(gen_grant_carry___d284));
  module_gen_grant_carry instance_gen_grant_carry_9(.gen_grant_carry_c(gen_grant_carry___d74[0]),
						    .gen_grant_carry_r(output_arbs_1_select_requests[1]),
						    .gen_grant_carry_p(oas_1_token_BIT_1___h9627),
						    .gen_grant_carry(gen_grant_carry___d78));
  module_gen_grant_carry instance_gen_grant_carry_10(.gen_grant_carry_c(gen_grant_carry___d78[0]),
						     .gen_grant_carry_r(output_arbs_1_select_requests[2]),
						     .gen_grant_carry_p(oas_1_token_BIT_2___h9693),
						     .gen_grant_carry(gen_grant_carry___d82));
  module_gen_grant_carry instance_gen_grant_carry_11(.gen_grant_carry_c(gen_grant_carry___d82[0]),
						     .gen_grant_carry_r(output_arbs_1_select_requests[3]),
						     .gen_grant_carry_p(oas_1_token_BIT_3___h9759),
						     .gen_grant_carry(gen_grant_carry___d86));
  module_gen_grant_carry instance_gen_grant_carry_12(.gen_grant_carry_c(gen_grant_carry___d86[0]),
						     .gen_grant_carry_r(output_arbs_1_select_requests[4]),
						     .gen_grant_carry_p(oas_1_token_BIT_4___h9825),
						     .gen_grant_carry(gen_grant_carry___d90));
  module_gen_grant_carry instance_gen_grant_carry_13(.gen_grant_carry_c(gen_grant_carry___d90[0]),
						     .gen_grant_carry_r(output_arbs_1_select_requests[0]),
						     .gen_grant_carry_p(oas_1_token_BIT_0___h9561),
						     .gen_grant_carry(gen_grant_carry___d93));
  module_gen_grant_carry instance_gen_grant_carry_14(.gen_grant_carry_c(gen_grant_carry___d93[0]),
						     .gen_grant_carry_r(output_arbs_1_select_requests[1]),
						     .gen_grant_carry_p(oas_1_token_BIT_1___h9627),
						     .gen_grant_carry(gen_grant_carry___d95));
  module_gen_grant_carry instance_gen_grant_carry_15(.gen_grant_carry_c(gen_grant_carry___d95[0]),
						     .gen_grant_carry_r(output_arbs_1_select_requests[2]),
						     .gen_grant_carry_p(oas_1_token_BIT_2___h9693),
						     .gen_grant_carry(gen_grant_carry___d97));
  module_gen_grant_carry instance_gen_grant_carry_16(.gen_grant_carry_c(gen_grant_carry___d97[0]),
						     .gen_grant_carry_r(output_arbs_1_select_requests[3]),
						     .gen_grant_carry_p(oas_1_token_BIT_3___h9759),
						     .gen_grant_carry(gen_grant_carry___d99));
  module_gen_grant_carry instance_gen_grant_carry_17(.gen_grant_carry_c(gen_grant_carry___d99[0]),
						     .gen_grant_carry_r(output_arbs_1_select_requests[4]),
						     .gen_grant_carry_p(oas_1_token_BIT_4___h9825),
						     .gen_grant_carry(gen_grant_carry___d101));
  module_gen_grant_carry instance_gen_grant_carry_1(.gen_grant_carry_c(gen_grant_carry___d4[0]),
						    .gen_grant_carry_r(output_arbs_0_select_requests[1]),
						    .gen_grant_carry_p(oas_0_token_BIT_1___h4647),
						    .gen_grant_carry(gen_grant_carry___d8));
  module_gen_grant_carry instance_gen_grant_carry_0(.gen_grant_carry_c(gen_grant_carry___d8[0]),
						    .gen_grant_carry_r(output_arbs_0_select_requests[2]),
						    .gen_grant_carry_p(oas_0_token_BIT_2___h4713),
						    .gen_grant_carry(gen_grant_carry___d12));
  module_gen_grant_carry instance_gen_grant_carry_2(.gen_grant_carry_c(gen_grant_carry___d12[0]),
						    .gen_grant_carry_r(output_arbs_0_select_requests[3]),
						    .gen_grant_carry_p(oas_0_token_BIT_3___h4779),
						    .gen_grant_carry(gen_grant_carry___d16));
  module_gen_grant_carry instance_gen_grant_carry_3(.gen_grant_carry_c(gen_grant_carry___d16[0]),
						    .gen_grant_carry_r(output_arbs_0_select_requests[4]),
						    .gen_grant_carry_p(oas_0_token_BIT_4___h4845),
						    .gen_grant_carry(gen_grant_carry___d20));
  module_gen_grant_carry instance_gen_grant_carry_4(.gen_grant_carry_c(gen_grant_carry___d20[0]),
						    .gen_grant_carry_r(output_arbs_0_select_requests[0]),
						    .gen_grant_carry_p(oas_0_token_BIT_0___h4581),
						    .gen_grant_carry(gen_grant_carry___d23));
  module_gen_grant_carry instance_gen_grant_carry_5(.gen_grant_carry_c(gen_grant_carry___d23[0]),
						    .gen_grant_carry_r(output_arbs_0_select_requests[1]),
						    .gen_grant_carry_p(oas_0_token_BIT_1___h4647),
						    .gen_grant_carry(gen_grant_carry___d25));
  module_gen_grant_carry instance_gen_grant_carry_6(.gen_grant_carry_c(gen_grant_carry___d25[0]),
						    .gen_grant_carry_r(output_arbs_0_select_requests[2]),
						    .gen_grant_carry_p(oas_0_token_BIT_2___h4713),
						    .gen_grant_carry(gen_grant_carry___d27));
  module_gen_grant_carry instance_gen_grant_carry_7(.gen_grant_carry_c(gen_grant_carry___d27[0]),
						    .gen_grant_carry_r(output_arbs_0_select_requests[3]),
						    .gen_grant_carry_p(oas_0_token_BIT_3___h4779),
						    .gen_grant_carry(gen_grant_carry___d29));
  module_gen_grant_carry instance_gen_grant_carry_8(.gen_grant_carry_c(gen_grant_carry___d29[0]),
						    .gen_grant_carry_r(output_arbs_0_select_requests[4]),
						    .gen_grant_carry_p(oas_0_token_BIT_4___h4845),
						    .gen_grant_carry(gen_grant_carry___d31));
  module_gen_grant_carry instance_gen_grant_carry_18(.gen_grant_carry_c(gen_grant_carry___d144[0]),
						     .gen_grant_carry_r(output_arbs_2_select_requests[1]),
						     .gen_grant_carry_p(oas_2_token_BIT_1___h14604),
						     .gen_grant_carry(gen_grant_carry___d148));
  module_gen_grant_carry instance_gen_grant_carry_19(.gen_grant_carry_c(gen_grant_carry___d148[0]),
						     .gen_grant_carry_r(output_arbs_2_select_requests[2]),
						     .gen_grant_carry_p(oas_2_token_BIT_2___h14670),
						     .gen_grant_carry(gen_grant_carry___d152));
  module_gen_grant_carry instance_gen_grant_carry_20(.gen_grant_carry_c(gen_grant_carry___d152[0]),
						     .gen_grant_carry_r(output_arbs_2_select_requests[3]),
						     .gen_grant_carry_p(oas_2_token_BIT_3___h14736),
						     .gen_grant_carry(gen_grant_carry___d156));
  module_gen_grant_carry instance_gen_grant_carry_21(.gen_grant_carry_c(gen_grant_carry___d156[0]),
						     .gen_grant_carry_r(output_arbs_2_select_requests[4]),
						     .gen_grant_carry_p(oas_2_token_BIT_4___h14802),
						     .gen_grant_carry(gen_grant_carry___d160));
  module_gen_grant_carry instance_gen_grant_carry_22(.gen_grant_carry_c(gen_grant_carry___d160[0]),
						     .gen_grant_carry_r(output_arbs_2_select_requests[0]),
						     .gen_grant_carry_p(oas_2_token_BIT_0___h14538),
						     .gen_grant_carry(gen_grant_carry___d163));
  module_gen_grant_carry instance_gen_grant_carry_23(.gen_grant_carry_c(gen_grant_carry___d163[0]),
						     .gen_grant_carry_r(output_arbs_2_select_requests[1]),
						     .gen_grant_carry_p(oas_2_token_BIT_1___h14604),
						     .gen_grant_carry(gen_grant_carry___d165));
  module_gen_grant_carry instance_gen_grant_carry_24(.gen_grant_carry_c(gen_grant_carry___d165[0]),
						     .gen_grant_carry_r(output_arbs_2_select_requests[2]),
						     .gen_grant_carry_p(oas_2_token_BIT_2___h14670),
						     .gen_grant_carry(gen_grant_carry___d167));
  module_gen_grant_carry instance_gen_grant_carry_25(.gen_grant_carry_c(gen_grant_carry___d167[0]),
						     .gen_grant_carry_r(output_arbs_2_select_requests[3]),
						     .gen_grant_carry_p(oas_2_token_BIT_3___h14736),
						     .gen_grant_carry(gen_grant_carry___d169));
  module_gen_grant_carry instance_gen_grant_carry_26(.gen_grant_carry_c(gen_grant_carry___d169[0]),
						     .gen_grant_carry_r(output_arbs_2_select_requests[4]),
						     .gen_grant_carry_p(oas_2_token_BIT_4___h14802),
						     .gen_grant_carry(gen_grant_carry___d171));
  module_gen_grant_carry instance_gen_grant_carry_27(.gen_grant_carry_c(gen_grant_carry___d214[0]),
						     .gen_grant_carry_r(output_arbs_3_select_requests[1]),
						     .gen_grant_carry_p(oas_3_token_BIT_1___h19581),
						     .gen_grant_carry(gen_grant_carry___d218));
  module_gen_grant_carry instance_gen_grant_carry_28(.gen_grant_carry_c(gen_grant_carry___d218[0]),
						     .gen_grant_carry_r(output_arbs_3_select_requests[2]),
						     .gen_grant_carry_p(oas_3_token_BIT_2___h19647),
						     .gen_grant_carry(gen_grant_carry___d222));
  module_gen_grant_carry instance_gen_grant_carry_29(.gen_grant_carry_c(gen_grant_carry___d222[0]),
						     .gen_grant_carry_r(output_arbs_3_select_requests[3]),
						     .gen_grant_carry_p(oas_3_token_BIT_3___h19713),
						     .gen_grant_carry(gen_grant_carry___d226));
  module_gen_grant_carry instance_gen_grant_carry_30(.gen_grant_carry_c(gen_grant_carry___d226[0]),
						     .gen_grant_carry_r(output_arbs_3_select_requests[4]),
						     .gen_grant_carry_p(oas_3_token_BIT_4___h19779),
						     .gen_grant_carry(gen_grant_carry___d230));
  module_gen_grant_carry instance_gen_grant_carry_31(.gen_grant_carry_c(gen_grant_carry___d230[0]),
						     .gen_grant_carry_r(output_arbs_3_select_requests[0]),
						     .gen_grant_carry_p(oas_3_token_BIT_0___h19515),
						     .gen_grant_carry(gen_grant_carry___d233));
  module_gen_grant_carry instance_gen_grant_carry_32(.gen_grant_carry_c(gen_grant_carry___d233[0]),
						     .gen_grant_carry_r(output_arbs_3_select_requests[1]),
						     .gen_grant_carry_p(oas_3_token_BIT_1___h19581),
						     .gen_grant_carry(gen_grant_carry___d235));
  module_gen_grant_carry instance_gen_grant_carry_33(.gen_grant_carry_c(gen_grant_carry___d235[0]),
						     .gen_grant_carry_r(output_arbs_3_select_requests[2]),
						     .gen_grant_carry_p(oas_3_token_BIT_2___h19647),
						     .gen_grant_carry(gen_grant_carry___d237));
  module_gen_grant_carry instance_gen_grant_carry_34(.gen_grant_carry_c(gen_grant_carry___d237[0]),
						     .gen_grant_carry_r(output_arbs_3_select_requests[3]),
						     .gen_grant_carry_p(oas_3_token_BIT_3___h19713),
						     .gen_grant_carry(gen_grant_carry___d239));
  module_gen_grant_carry instance_gen_grant_carry_35(.gen_grant_carry_c(gen_grant_carry___d239[0]),
						     .gen_grant_carry_r(output_arbs_3_select_requests[4]),
						     .gen_grant_carry_p(oas_3_token_BIT_4___h19779),
						     .gen_grant_carry(gen_grant_carry___d241));
  module_gen_grant_carry instance_gen_grant_carry_36(.gen_grant_carry_c(gen_grant_carry___d284[0]),
						     .gen_grant_carry_r(output_arbs_4_select_requests[1]),
						     .gen_grant_carry_p(oas_4_token_BIT_1___h24558),
						     .gen_grant_carry(gen_grant_carry___d288));
  module_gen_grant_carry instance_gen_grant_carry_37(.gen_grant_carry_c(gen_grant_carry___d288[0]),
						     .gen_grant_carry_r(output_arbs_4_select_requests[2]),
						     .gen_grant_carry_p(oas_4_token_BIT_2___h24624),
						     .gen_grant_carry(gen_grant_carry___d292));
  module_gen_grant_carry instance_gen_grant_carry_38(.gen_grant_carry_c(gen_grant_carry___d292[0]),
						     .gen_grant_carry_r(output_arbs_4_select_requests[3]),
						     .gen_grant_carry_p(oas_4_token_BIT_3___h24690),
						     .gen_grant_carry(gen_grant_carry___d296));
  module_gen_grant_carry instance_gen_grant_carry_39(.gen_grant_carry_c(gen_grant_carry___d296[0]),
						     .gen_grant_carry_r(output_arbs_4_select_requests[4]),
						     .gen_grant_carry_p(oas_4_token_BIT_4___h24756),
						     .gen_grant_carry(gen_grant_carry___d300));
  module_gen_grant_carry instance_gen_grant_carry_40(.gen_grant_carry_c(gen_grant_carry___d300[0]),
						     .gen_grant_carry_r(output_arbs_4_select_requests[0]),
						     .gen_grant_carry_p(oas_4_token_BIT_0___h24492),
						     .gen_grant_carry(gen_grant_carry___d303));
  module_gen_grant_carry instance_gen_grant_carry_41(.gen_grant_carry_c(gen_grant_carry___d303[0]),
						     .gen_grant_carry_r(output_arbs_4_select_requests[1]),
						     .gen_grant_carry_p(oas_4_token_BIT_1___h24558),
						     .gen_grant_carry(gen_grant_carry___d305));
  module_gen_grant_carry instance_gen_grant_carry_42(.gen_grant_carry_c(gen_grant_carry___d305[0]),
						     .gen_grant_carry_r(output_arbs_4_select_requests[2]),
						     .gen_grant_carry_p(oas_4_token_BIT_2___h24624),
						     .gen_grant_carry(gen_grant_carry___d307));
  module_gen_grant_carry instance_gen_grant_carry_43(.gen_grant_carry_c(gen_grant_carry___d307[0]),
						     .gen_grant_carry_r(output_arbs_4_select_requests[3]),
						     .gen_grant_carry_p(oas_4_token_BIT_3___h24690),
						     .gen_grant_carry(gen_grant_carry___d309));
  module_gen_grant_carry instance_gen_grant_carry_44(.gen_grant_carry_c(gen_grant_carry___d309[0]),
						     .gen_grant_carry_r(output_arbs_4_select_requests[4]),
						     .gen_grant_carry_p(oas_4_token_BIT_4___h24756),
						     .gen_grant_carry(gen_grant_carry___d311));
  assign NOT_gen_grant_carry_00_BIT_1_01_14_AND_NOT_gen_ETC___d328 =
	     !gen_grant_carry___d300[1] && !gen_grant_carry___d311[1] &&
	     !gen_grant_carry___d296[1] &&
	     !gen_grant_carry___d309[1] &&
	     (gen_grant_carry___d292[1] || gen_grant_carry___d307[1]) ;
  assign NOT_gen_grant_carry_00_BIT_1_01_14_AND_NOT_gen_ETC___d348 =
	     !gen_grant_carry___d300[1] && !gen_grant_carry___d311[1] &&
	     !gen_grant_carry___d296[1] &&
	     !gen_grant_carry___d309[1] &&
	     NOT_gen_grant_carry_92_BIT_1_24_30_AND_NOT_gen_ETC___d346 ;
  assign NOT_gen_grant_carry_0_BIT_1_1_04_AND_NOT_gen_g_ETC___d118 =
	     !gen_grant_carry___d90[1] && !gen_grant_carry___d101[1] &&
	     !gen_grant_carry___d86[1] &&
	     !gen_grant_carry___d99[1] &&
	     (gen_grant_carry___d82[1] || gen_grant_carry___d97[1]) ;
  assign NOT_gen_grant_carry_0_BIT_1_1_04_AND_NOT_gen_g_ETC___d138 =
	     !gen_grant_carry___d90[1] && !gen_grant_carry___d101[1] &&
	     !gen_grant_carry___d86[1] &&
	     !gen_grant_carry___d99[1] &&
	     NOT_gen_grant_carry_2_BIT_1_14_20_AND_NOT_gen__ETC___d136 ;
  assign NOT_gen_grant_carry_0_BIT_1_1_4_AND_NOT_gen_gr_ETC___d48 =
	     !gen_grant_carry___d20[1] && !gen_grant_carry___d31[1] &&
	     !gen_grant_carry___d16[1] &&
	     !gen_grant_carry___d29[1] &&
	     (gen_grant_carry___d12[1] || gen_grant_carry___d27[1]) ;
  assign NOT_gen_grant_carry_0_BIT_1_1_4_AND_NOT_gen_gr_ETC___d68 =
	     !gen_grant_carry___d20[1] && !gen_grant_carry___d31[1] &&
	     !gen_grant_carry___d16[1] &&
	     !gen_grant_carry___d29[1] &&
	     NOT_gen_grant_carry_2_BIT_1_4_0_AND_NOT_gen_gr_ETC___d66 ;
  assign NOT_gen_grant_carry_22_BIT_1_54_60_AND_NOT_gen_ETC___d276 =
	     !gen_grant_carry___d222[1] && !gen_grant_carry___d237[1] &&
	     !gen_grant_carry___d218[1] &&
	     !gen_grant_carry___d235[1] &&
	     (gen_grant_carry___d214[1] || gen_grant_carry___d233[1]) ;
  assign NOT_gen_grant_carry_26_BIT_1_47_51_AND_NOT_gen_ETC___d267 =
	     !gen_grant_carry___d226[1] && !gen_grant_carry___d239[1] &&
	     !gen_grant_carry___d222[1] &&
	     !gen_grant_carry___d237[1] &&
	     (gen_grant_carry___d218[1] || gen_grant_carry___d235[1]) ;
  assign NOT_gen_grant_carry_2_BIT_1_14_20_AND_NOT_gen__ETC___d136 =
	     !gen_grant_carry___d82[1] && !gen_grant_carry___d97[1] &&
	     !gen_grant_carry___d78[1] &&
	     !gen_grant_carry___d95[1] &&
	     (gen_grant_carry___d74[1] || gen_grant_carry___d93[1]) ;
  assign NOT_gen_grant_carry_2_BIT_1_4_0_AND_NOT_gen_gr_ETC___d66 =
	     !gen_grant_carry___d12[1] && !gen_grant_carry___d27[1] &&
	     !gen_grant_carry___d8[1] &&
	     !gen_grant_carry___d25[1] &&
	     (gen_grant_carry___d4[1] || gen_grant_carry___d23[1]) ;
  assign NOT_gen_grant_carry_30_BIT_1_31_44_AND_NOT_gen_ETC___d258 =
	     !gen_grant_carry___d230[1] && !gen_grant_carry___d241[1] &&
	     !gen_grant_carry___d226[1] &&
	     !gen_grant_carry___d239[1] &&
	     (gen_grant_carry___d222[1] || gen_grant_carry___d237[1]) ;
  assign NOT_gen_grant_carry_30_BIT_1_31_44_AND_NOT_gen_ETC___d278 =
	     !gen_grant_carry___d230[1] && !gen_grant_carry___d241[1] &&
	     !gen_grant_carry___d226[1] &&
	     !gen_grant_carry___d239[1] &&
	     NOT_gen_grant_carry_22_BIT_1_54_60_AND_NOT_gen_ETC___d276 ;
  assign NOT_gen_grant_carry_52_BIT_1_84_90_AND_NOT_gen_ETC___d206 =
	     !gen_grant_carry___d152[1] && !gen_grant_carry___d167[1] &&
	     !gen_grant_carry___d148[1] &&
	     !gen_grant_carry___d165[1] &&
	     (gen_grant_carry___d144[1] || gen_grant_carry___d163[1]) ;
  assign NOT_gen_grant_carry_56_BIT_1_77_81_AND_NOT_gen_ETC___d197 =
	     !gen_grant_carry___d156[1] && !gen_grant_carry___d169[1] &&
	     !gen_grant_carry___d152[1] &&
	     !gen_grant_carry___d167[1] &&
	     (gen_grant_carry___d148[1] || gen_grant_carry___d165[1]) ;
  assign NOT_gen_grant_carry_60_BIT_1_61_74_AND_NOT_gen_ETC___d188 =
	     !gen_grant_carry___d160[1] && !gen_grant_carry___d171[1] &&
	     !gen_grant_carry___d156[1] &&
	     !gen_grant_carry___d169[1] &&
	     (gen_grant_carry___d152[1] || gen_grant_carry___d167[1]) ;
  assign NOT_gen_grant_carry_60_BIT_1_61_74_AND_NOT_gen_ETC___d208 =
	     !gen_grant_carry___d160[1] && !gen_grant_carry___d171[1] &&
	     !gen_grant_carry___d156[1] &&
	     !gen_grant_carry___d169[1] &&
	     NOT_gen_grant_carry_52_BIT_1_84_90_AND_NOT_gen_ETC___d206 ;
  assign NOT_gen_grant_carry_6_BIT_1_07_11_AND_NOT_gen__ETC___d127 =
	     !gen_grant_carry___d86[1] && !gen_grant_carry___d99[1] &&
	     !gen_grant_carry___d82[1] &&
	     !gen_grant_carry___d97[1] &&
	     (gen_grant_carry___d78[1] || gen_grant_carry___d95[1]) ;
  assign NOT_gen_grant_carry_6_BIT_1_7_1_AND_NOT_gen_gr_ETC___d57 =
	     !gen_grant_carry___d16[1] && !gen_grant_carry___d29[1] &&
	     !gen_grant_carry___d12[1] &&
	     !gen_grant_carry___d27[1] &&
	     (gen_grant_carry___d8[1] || gen_grant_carry___d25[1]) ;
  assign NOT_gen_grant_carry_92_BIT_1_24_30_AND_NOT_gen_ETC___d346 =
	     !gen_grant_carry___d292[1] && !gen_grant_carry___d307[1] &&
	     !gen_grant_carry___d288[1] &&
	     !gen_grant_carry___d305[1] &&
	     (gen_grant_carry___d284[1] || gen_grant_carry___d303[1]) ;
  assign NOT_gen_grant_carry_96_BIT_1_17_21_AND_NOT_gen_ETC___d337 =
	     !gen_grant_carry___d296[1] && !gen_grant_carry___d309[1] &&
	     !gen_grant_carry___d292[1] &&
	     !gen_grant_carry___d307[1] &&
	     (gen_grant_carry___d288[1] || gen_grant_carry___d305[1]) ;
  assign oas_0_token_BIT_0___h4581 = oas_0_token[0] ;
  assign oas_0_token_BIT_1___h4647 = oas_0_token[1] ;
  assign oas_0_token_BIT_2___h4713 = oas_0_token[2] ;
  assign oas_0_token_BIT_3___h4779 = oas_0_token[3] ;
  assign oas_0_token_BIT_4___h4845 = oas_0_token[4] ;
  assign oas_1_token_BIT_0___h9561 = oas_1_token[0] ;
  assign oas_1_token_BIT_1___h9627 = oas_1_token[1] ;
  assign oas_1_token_BIT_2___h9693 = oas_1_token[2] ;
  assign oas_1_token_BIT_3___h9759 = oas_1_token[3] ;
  assign oas_1_token_BIT_4___h9825 = oas_1_token[4] ;
  assign oas_2_token_BIT_0___h14538 = oas_2_token[0] ;
  assign oas_2_token_BIT_1___h14604 = oas_2_token[1] ;
  assign oas_2_token_BIT_2___h14670 = oas_2_token[2] ;
  assign oas_2_token_BIT_3___h14736 = oas_2_token[3] ;
  assign oas_2_token_BIT_4___h14802 = oas_2_token[4] ;
  assign oas_3_token_BIT_0___h19515 = oas_3_token[0] ;
  assign oas_3_token_BIT_1___h19581 = oas_3_token[1] ;
  assign oas_3_token_BIT_2___h19647 = oas_3_token[2] ;
  assign oas_3_token_BIT_3___h19713 = oas_3_token[3] ;
  assign oas_3_token_BIT_4___h19779 = oas_3_token[4] ;
  assign oas_4_token_BIT_0___h24492 = oas_4_token[0] ;
  assign oas_4_token_BIT_1___h24558 = oas_4_token[1] ;
  assign oas_4_token_BIT_2___h24624 = oas_4_token[2] ;
  assign oas_4_token_BIT_3___h24690 = oas_4_token[3] ;
  assign oas_4_token_BIT_4___h24756 = oas_4_token[4] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        oas_0_token <= `BSV_ASSIGNMENT_DELAY 5'd1;
	oas_1_token <= `BSV_ASSIGNMENT_DELAY 5'd2;
	oas_2_token <= `BSV_ASSIGNMENT_DELAY 5'd4;
	oas_3_token <= `BSV_ASSIGNMENT_DELAY 5'd8;
	oas_4_token <= `BSV_ASSIGNMENT_DELAY 5'd16;
      end
    else
      begin
        if (oas_0_token$EN)
	  oas_0_token <= `BSV_ASSIGNMENT_DELAY oas_0_token$D_IN;
	if (oas_1_token$EN)
	  oas_1_token <= `BSV_ASSIGNMENT_DELAY oas_1_token$D_IN;
	if (oas_2_token$EN)
	  oas_2_token <= `BSV_ASSIGNMENT_DELAY oas_2_token$D_IN;
	if (oas_3_token$EN)
	  oas_3_token <= `BSV_ASSIGNMENT_DELAY oas_3_token$D_IN;
	if (oas_4_token$EN)
	  oas_4_token <= `BSV_ASSIGNMENT_DELAY oas_4_token$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    oas_0_token = 5'h0A;
    oas_1_token = 5'h0A;
    oas_2_token = 5'h0A;
    oas_3_token = 5'h0A;
    oas_4_token = 5'h0A;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkRouterOutputArbitersRoundRobin

