//
// Generated by Bluespec Compiler, version 2025.01.1-9-g76db531e (build 76db531e)
//
// On Mon Jul 28 19:05:15 PDT 2025
//
//
// Ports:
// Name                         I/O  size props
// select                         O     8
// CLK                            I     1 unused
// RST_N                          I     1 unused
// select_requests                I     8
// EN_next                        I     1 unused
//
// Combinational paths from inputs to outputs:
//   select_requests -> select
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTestArbiter8(CLK,
		      RST_N,

		      select_requests,
		      select,

		      EN_next);
  input  CLK;
  input  RST_N;

  // value method select
  input  [7 : 0] select_requests;
  output [7 : 0] select;

  // action method next
  input  EN_next;

  // signals for module outputs
  wire [7 : 0] select;

  // value method select
  assign select =
	     { !select_requests[1] && !select_requests[0] &&
	       select_requests[7],
	       !select_requests[1] && !select_requests[0] &&
	       !select_requests[7] &&
	       select_requests[6],
	       !select_requests[1] && !select_requests[0] &&
	       !select_requests[7] &&
	       !select_requests[6] &&
	       select_requests[5],
	       !select_requests[1] && !select_requests[0] &&
	       !select_requests[7] &&
	       !select_requests[6] &&
	       !select_requests[5] &&
	       select_requests[4],
	       !select_requests[1] && !select_requests[0] &&
	       !select_requests[7] &&
	       !select_requests[6] &&
	       !select_requests[5] &&
	       !select_requests[4] &&
	       select_requests[3],
	       !select_requests[1] && !select_requests[0] &&
	       !select_requests[7] &&
	       !select_requests[6] &&
	       !select_requests[5] &&
	       !select_requests[4] &&
	       !select_requests[3] &&
	       select_requests[2],
	       select_requests[1],
	       !select_requests[1] && select_requests[0] } ;
endmodule  // mkTestArbiter8

